[package]
name = "inline_cache"
version = "0.1.0"
edition = "2024"

[features]
force_fallback_impl = []

[dependencies]
bytemuck = "1.22.0"
cfg-if = "1.0.0"

[dev-dependencies]
bytemuck = { version = "1.22.0", features = ["zeroable_atomics"] }
